### ISSUE TITLE
'Blocky' maps and certificate problems

### ISSUE THREAD

**Issue by 3DSpotters** [albar965/littlenavmap#980]
Hi,

I see 2 problems, with the current LNM v2.8.7 on Linux, that I cannot solve by myself ...

1. Blocky maps - the problem is for different themes when zoomed in, status bar showing both "Loading" or "Done".
![LNM_Blocky_maps_LNM_2023-01-06_10-34-06](https://user-images.githubusercontent.com/47834083/210975159-7121826b-d81c-4fae-8a1e-929c3f56a821.png)
In the same moment the "original" site of OpenStreetMap shows the map properly:
![LNM_Blocky_maps_OSM_2023-01-06_10-39-42](https://user-images.githubusercontent.com/47834083/210975283-5fa4aa20-3be1-4118-9278-a1e87ab5b44a.png)

2. Certificate problem - ?
![LNM Certificate problems_2023-01-06_10-41-46](https://user-images.githubusercontent.com/47834083/210975354-4c0f43b6-a9fd-45d5-9131-046e7b5910e7.png)

**Comment by albar965** [comment]
This should fix it: https://github.com/albar965/littlenavmap/releases/download/v2.8.7/LittleNavmap-linux-22.04-2.8.7-openssl-1.1.tar.gz

Fix will be included in the next LNM 2.8.8.

Alex

**Comment by 3DSpotters** [comment]
YESSS !
The above patch worked for both problems :)

Thank you very much !

**Comment by Gunpilot399** [comment]
I still have this blocky prob when I zoom in for detail...running 2.8.8 on Windows 11
![LNM prob](https://user-images.githubusercontent.com/125111402/218241204-05967727-8548-4d3b-a1ff-650a94e10402.jpg)

**Comment by Gunpilot399** [comment]
Any assistance would be greatly appreciated

**Comment by albar965** [comment]
> I still have this blocky prob when I zoom in for detail...running 2.8.8 on Windows 11

What does LNM menu -> `Help` -> `About Little Navmap` say about OpenSSL? 

The libraries `libcrypto-1_1-x64.dll` and `libssl-1_1-x64.dll` are included in the download. Are these quarantined by anti-virus or blocked by Windows for any reason?
